name: Check Latest OpenVPN Version

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Get the latest version of OpenVPN
        run: |
          curl -sSLf https://api.github.com/repos/openvpn/openvpn/git/refs/tags|jq -r .[].ref|cut -d"/" -f3|grep -E -ve "alpha|beta|branch|rc|RC"|sort -V|tail -n1|sed "s/v//g" > version
          echo "OPENVPN_VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: ${{ env.OPENVPN_VERSION }}'
